# One should use this script if one wants to train a model for the attitude determination task

project_name: mcd_attitude_estimator # Name of the WandB project
group_name: drop_10 # Training procedures will be grouped by the group name
model_dir: saved_models
save_architecture: True
allow_resume: False
display_summary: True

# Anchors
batch_size: &batch_size 64
observations: &observations 4 # Number of observation vectors per sample
mcd_rate: &mcd_rate 0.1 # Dropout rate
parametrization: &parametrization dcm # Type of rotation parametrization. dcm' stands for Direction Cosine Matrix
architecture: &architecture mcd_attitude_estimator

model_name: !join [*architecture, "_", *observations, "_", !multiply [*mcd_rate, 100]]

dataset_params:
    handler: attitude_dataset
    val_ratio: 0.04
    test_ratio: 0.3
    batch_size: *batch_size
    num_samples: 8192
    num_observations: *observations
    parametrization: *parametrization 
    min_angle: -180
    max_angle: 180
    add_noise: True
    std_range:
        - 1.0e-6
        - 1.0e-2

train_params:
    metrics:
        - wahba_error
        - geodesic_error

    loss: geodesic_loss

    monitor: val_wahba_error

    epochs: 2000

    hyperparams:
        batch_size: *batch_size
        mcd_rate: *mcd_rate
        parametrization: *parametrization
